# Note: additional setup is required, see https://www.jenkins.io/redirect/continuous-delivery-of-plugins

name: maven-cd
on:
  workflow_call:
    inputs:
      validate_only:
        type: string
        required: false
        description: |
          Validate with release drafter only
          => Skip release job
        default: false
    secrets:
      MAVEN_USERNAME:
        required: true
        description: Maven username used for deploying the plugin jar to Jenkins Artifactory Repository
      MAVEN_TOKEN:
        required: true
        description: Maven token used for deploying the plugin jar to Jenkins Artifactory Repository
jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      # If this is being changed, then align step log-should_release-details below!
      should_release: ${{ inputs.validate_only == 'false' && steps.verify-ci-status.outputs.result == 'success' && steps.interesting-categories.outputs.interesting == 'true' }}
    steps:
      - name: Verify CI status
        uses: jenkins-infra/verify-ci-status-action@v1.2.2
        id: verify-ci-status
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output_result: true
      - name: Release Drafter
        uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6
        id: draft
        if: steps.verify-ci-status.outputs.result == 'success'
        with:
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check interesting categories
        uses: jenkins-infra/interesting-category-action@v1.2.1
        id: interesting-categories
        if: steps.verify-ci-status.outputs.result == 'success'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_DRAFT_BODY: ${{ steps.draft.outputs.body }}
      - name: Log should_release details
        id: log-should_release-details
        run: |
          MD_CODE='```'
          cat << END_OF_SUMMARY | tee -a $GITHUB_STEP_SUMMARY
          ## Job Filter Summary
          ${MD_CODE}
          ================================
          Release job filter details:
                    VALIDATE_ONLY: ${VALIDATE_ONLY}
                        CI_STATUS: ${CI_STATUS}
             INTERESTING_CATEGORY: ${INTERESTING_CATEGORY}
          --------------------------------
          =>       SHOULD_RELEASE: ${SHOULD_RELEASE}
          ================================
          ${MD_CODE}
          END_OF_SUMMARY
        env:
          VALIDATE_ONLY: ${{ inputs.validate_only }}
          CI_STATUS: ${{ steps.verify-ci-status.outputs.result }}
          INTERESTING_CATEGORY: ${{ steps.interesting-categories.outputs.interesting }}
          # This must be equal to output should_release of job validate above!
          SHOULD_RELEASE: ${{ inputs.validate_only == 'false' && steps.verify-ci-status.outputs.result == 'success' && steps.interesting-categories.outputs.interesting == 'true' }}
  release:
    runs-on: ubuntu-latest
    needs: [validate]
    if: needs.validate.outputs.should_release == 'true'
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Release
        uses: jenkins-infra/jenkins-maven-cd-action@v1.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
